language: node_js
node_js:
 - "10"
script:
  - npm run build
cache: npm
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 8b2128f09f768a7b6f2880705c2601d603278a88
  keep-history: true
  local-dir: dist
  on:
    branch: master
