# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the gh-pages branch
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Deploy to Heroku
  # You may pin to the exact commit or the version.
  # uses: AkhileshNS/heroku-deploy@2c4b0a147142a9c38116962bc84a38ed9c2d4f52
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
    # This will be used for authentication. You can find it in your heroku homepage account settings
             heroku_api_key: 2db6fcd9-4dcd-4a0d-9092-44f353c9c27d
    # Email that you use with heroku
             heroku_email: 24buermliam@detlakes.k12.mn.us
    # The appname to use for deploying/updating
             heroku_app_name:  nbseditor-prebuild
    # The branch that you would like to deploy to Heroku
             branch: HEAD
    # Set this to true if you don't want to use --force when switching branches
             dontuseforce: false
    # Will deploy using Dockerfile in project root.
             usedocker: false
    # Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled
             docker_heroku_process_type: web
    # Time (in seconds) to wait before performing healthcheck
             delay: 0
